### ISSUE TITLE
Typedef / Partial Specialization Problems with Eigen

### ISSUE THREAD

**Issue by dmcconachie** [WPI-ARC/arc_utilities#4]
So I ran into an irritating problem using `arc_utilities/eigen_helpers.hpp` in conjunction with `sdf_tools/sdf_builder.hpp`

One of the files included by `sdf_tools/sdf_builder.hpp` includes `<Eigen/StdVector>`.  Depending on the include order, this causes problems.

The following code does not compile.

```
#include <arc_utilities/eigen_helpers.hpp>
#include <Eigen/StdVector>

int main(int argc, char** argv)
{
    (void)argc;
    (void)argv;
    return 0;
}
```

If I switch the include order so that `<Eigen/StdVector>` is the first include, everything compiles with no problem.

So I've currently tweaked my include order to put `sdf_tools/sdf_builder.hpp' before the files that include `arc_utilities/eigen_helpers.hpp` (I don't include it directly) as a work around, however this is not ideal.

The internet tells me this is probably a known issue already, but we may want to address it directly in arc_utlities anyway, as the last comment in the linked Eigen bugzilla seems to indicate that while Eigen has addressed this in some fashion in the devel branch, who knows how long till that makes it out to us.

https://github.com/strands-project/v4r/issues/39

That and the instructions for using Eigen types with STL containers does say to include <Eigen/StdVector>

http://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html#vector_spec

**Comment by calderpg** [comment]
So simply adding `Eigen/StdVector` to `arc_utilities/eigen_helpers.hpp` appears to break the ability to use initializer lists on the typedef'd containters:

```
test_arc_utilities.cpp:34:
error: no matching function for call to 'std::vector<Eigen::Matrix<double, 3, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 3, 1> > >::vector(<brace-enclosed initializer list>)'
EigenHelpers::VectorVector3d testvecs{testvec1, testvec2, testvec3, testvec4, testvec5, testvec6, testvec7, testvec8};
```

The root issue appears to be this:

```
arc_utilities/src/test_arc_utilities.cpp:34:
note: cannot convert 'testvec1' (type 'Eigen::Vector3d {aka Eigen::Matrix<double, 3, 1>}') to type 'const allocator_type& {aka const Eigen::aligned_allocator_indirection<Eigen::Matrix<double, 3, 1> >&}'
EigenHelpers::VectorVector3d testvecs{testvec1, testvec2, testvec3, testvec4, testvec5, testvec6, testvec7, testvec8};
```

I really don't want to lose the ability to create these containers using initializer lists, if for no other reason than if something claims to be an std::vector, it should actually behave like one!

**Comment by dmcconachie** [comment]
I tried the same thing and found the same issue, so I punted on it for now and simply added <Eigen/StdVector> directly into the file that was having problems.

The Eigen reference page does include an alternative solution that could be tried.

**Comment by dmcconachie** [comment]
FWIW, I think that fixing a "include order matters" problem is worth it. The problem already exists in our codebase, it just hadn't been exposed yet.

```
#include <arc_utilities/eigen_helpers.hpp>
#include <sdf_tools/sdf_builder.hpp>
...
EigenHelpers::VectorVector4d test = {Eigen::Vector4d(1,1,1,1)};
```

Does not compile, nor does swapping the include order.  Something has to give.

**Comment by calderpg** [comment]
I ended up going ahead and adding `#include <Eigen/StdVector>` to `eigen_helpers.hpp` and removing all the uses of initializer lists. It's annoying not to be able to use them, but it's better than having include order issues.
